# Generated by Django 4.1.6 on 2023-10-03 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_officerent_description_officerent_rent_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officerent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='officerent',
            name='rent_amount',
        ),
        migrations.RemoveField(
            model_name='officerent',
            name='rent_date',
        ),
    ]
